--创建空表的 SQL 命令
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
id INTEGER PRIMARY KEY AUTHORIZATION,
username TEXT UNIQUE NOT NULL,
password TEXT NOT NULL);

CREATE TABLE post(
id INTEGER PRIMARY KEY AUTHORIZATION,
author_id INTEGER NOT NULL,
created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
title TEXT NOT NULL,
body TEXT NOT NULL,
FOREIGN KET (author_id) PEFERENCES user (id))